#ifndef E_TRASH_TALK_DATA_H
#define E_TRASH_TALK_DATA_H

// ============ [MOD] Trash Talk Phrase Database ============
// %N = player name placeholder

static const char* tt_onMyKill[] = {
    "ez","too slow","calculated","get rekt","not even close","outplayed",
    "sorry not sorry","that was free","gg wp... jk","rip bozo",
    "imagine dying there lol","skill issue","another one for the collection",
    "you walked right into that","i didnt even break a sweat",
    "that was personal","clean kill","ctrl+w for better rubber",
    "do you need a tutorial?","thats gotta hurt","skill gap is real",
    "natural selection","instant karma","i could do this blindfolded",
    "send the next one","speedrun any%","try minecraft instead",
    "was that supposed to be hard?","oops my finger slipped (it didnt)",
    "subscribe for more highlights","that was cleaner than my room",
    "and the crowd goes wild","domination complete","i am inevitable",
    "too easy need harder opponents","another day at the office",
    "they never learn","precision strike","flawless victory",
    "you call that a strategy?","thats what happens when you challenge me",
    "i barely moved lol","no survivors","target eliminated",
    "blink and youre dead","welcome to the shadow realm",
    "you just got recycled","that was a public service",
    "did that hurt? good","im just warming up","you were saying?",
    "you brought this upon yourself","express delivery to the graveyard",
    "another satisfied customer","game over for you",
    "that kill was sponsored by skill","i do this for fun btw",
    "you fought bravely... for 2 seconds","my highlight reel thanks you",
    "told you so","get good or get gone","any last words? too late",
    "thats what I thought","speed diff","reaction time diff",
    "skill check failed","your defense was mid","im on fire today",
    "cant stop wont stop","you should see my other kills",
    "another one down who's next","catching bodies all day",
    "you had your chance","this aint your day chief"
};

static const char* tt_onMyKillNamed[] = {
    "%N got deleted from the timeline","sorry %N that was too easy",
    "%N just got a free lesson","rest in pieces %N",
    "%N come back when you git gud","%N needs more practice",
    "%N that was embarrassing ngl","bye bye %N",
    "%N you tried your best... kinda","%N skill issue detected",
    "%N just got outclassed","%N welcome to my highlight reel",
    "%N never had a chance","%N i would say gg but it wasnt",
    "%N dont worry it happens to everyone","%N should watch tutorials",
    "%N better luck next life","%N get a better gaming chair",
    "%N you ok bro?","%N that wasnt even my final form",
    "%N google how to play tron","%N uninstall.exe launched",
    "%N thanks for the free point","%N just got express delivered",
    "%N maybe next time buddy","%N L + ratio + skill issue",
    "%N sit down please","%N just got a reality check",
    "%N speedrun to death any%","%N you peaked in the lobby",
    "%N was sacrificed for content","%N just became a statistic",
    "%N thought they had a chance lol","%N certified free kill",
    "%N nothing personal... ok maybe a little","%N take notes",
    "%N do you want me to go easier?","%N ragequit incoming?",
    "%N did you even try?","%N imagine losing to me haha jk... unless",
    "%N skill gap is astronomical","%N that was charity work",
    "%N was eliminated from the competition","%N got the tutorial experience",
    "%N wrong neighborhood","%N got turned into content"
};

static const char* tt_onMyDeath[] = {
    "lag","my cat stepped on keyboard","i let you have that one",
    "nice one ngl","ok that was clean","bruh","rubber glitch tbh",
    "gg","I was afk lol","first time playing btw",
    "wow such skill much wow","my mouse disconnected",
    "had to sneeze","internet provider hates me","clearly a bug",
    "I was testing a new strat","planned death for intel",
    "my finger slipped","i was letting you win","who moved my desk",
    "that was a sacrifice play","was answering a phone call",
    "someone knocked on my door","200 iq play you just dont see it yet",
    "all according to plan","tutorial round","my power flickered",
    "i blame global warming","gravity too strong","screen went black",
    "I disconnected mentally","hacks tho","i was making coffee",
    "fake death btw","tactical retreat gone wrong",
    "I zigged when I should have zagged","alt tabbed to check discord",
    "the sun was in my eyes","wifi went out for 0.001 seconds",
    "ok I wasnt ready","my monitor turned off I swear",
    "that was a practice round","does that even count?",
    "I was eating a sandwich","my chair broke at the worst moment",
    "plot armor expired","game is rigged","my rubber band snapped",
    "I did that on purpose for content","clearly outrubbered",
    "lag spike from another dimension","my cat pressed alt+f4",
    "someone hacked my keyboard","thats what I get for being nice",
    "gravity is a social construct","I was typing lol",
    "I forgot which key turns","my reflexes took a vacation",
    "that wall came out of nowhere I swear","skillful death btw",
    "meant to do that","I was distracted by how cool I look",
    "my gaming chair betrayed me","the prophecy was wrong",
    "I blame lag even though I have 5 ping","acceptable losses",
    "respawn diff","I was doing research","controlled demolition"
};

static const char* tt_onMyDeathNamed[] = {
    "%N got lucky this time","%N enjoy that it wont happen again",
    "%N ok I respect that","%N nice but I was lagging",
    "%N that was your peak performance","%N dont get used to it",
    "%N rematch right now 1v1","%N my keyboard failed",
    "%N you peaked right there","%N superbowl moment huh",
    "%N ok ok you win this round","%N save the replay its your best moment",
    "%N I will remember this","%N thats going in your highlight reel huh",
    "%N I was going easy on you","%N I wasnt even looking at the screen",
    "%N you got lucky and we both know it","%N revenge loading...",
    "%N thats cute enjoy it while it lasts","%N ill be back",
    "%N ok ngl that was actually good","%N you caught me slipping",
    "%N must feel nice huh","%N one kill doesnt make you good tho",
    "%N the prophecy says I win next time","%N mark my words"
};

static const char* tt_onEnemyDeath[] = {
    "rip","lmao","f","another one bites the dust","skill diff",
    "certified bruh moment","oof","thats tough","rage quit incoming",
    "big oof energy","press F","that was brutal","yikes",
    "and then there were fewer","gravity wins again",
    "the wall sends its regards","fatality","wasted",
    "they had a family","emotional damage","rest in pepperoni",
    "someone call an ambulance","plot armor ran out",
    "that was violent","ouch","back to lobby",
    "eliminated","gone but not forgotten","another one gone",
    "that was nasty","brutal","savage","that hurt to watch",
    "pain","the streets are dangerous","wall diff",
    "shoulda turned left","wrong move","thats gotta sting",
    "did anyone get that on camera","instant classic",
    "speedrun death any%","tactical error detected"
};

static const char* tt_onEnemyDeathNamed[] = {
    "rip %N lmao","%N just got served","%N bye bye",
    "%N ragequit in 3 2 1","pour one out for %N",
    "%N needs a hug after that","%N skill issue detected",
    "gg %N better luck next time","F in chat for %N",
    "%N that wall was clearly unfair","%N will remember that",
    "another day another %N death","%N just got wall checked",
    "%N the walls said no","%N certified bruh moment",
    "%N was sent to the shadow realm","%N you ok?",
    "%N maybe try turning next time","%N that was rough buddy",
    "%N down bad","%N got absolutely deleted",
    "%N just became a cautionary tale","%N rip in peace",
    "%N that was painful to watch","%N back to the lobby",
    "%N gone too soon","%N emotional damage received",
    "%N the wall won again","%N oof size: large",
    "%N has been eliminated from the competition"
};

static const char* tt_onMatchWin[] = {
    "GG WP everyone","ez game ez life","another W in the bag",
    "winning is a habit","all according to plan","flawless strategy",
    "teamwork makes the dream work","too clean","victory royale lol",
    "never in doubt","calculated from the start",
    "they fought well... we fought better","dominance established",
    "winner winner chicken dinner","add another trophy",
    "the better team won obviously","that was a good game ngl",
    "gg everyone that was fun","another match another W",
    "dont feel bad you tried your best","scoreboard doesnt lie",
    "we stay winning","wp everyone respect","hard fought but we got it",
    "clutch factor was on today","no losses only lessons... and this W",
    "undefeated era continues","the dynasty continues"
};

static const char* tt_onMatchLose[] = {
    "gg wp","good game","well played everyone","close game",
    "we go next","gg that was fun","respect to the winners",
    "we'll get em next time","learning experience","gg no cap",
    "ok they were good ngl","rematch?","close one gg",
    "lag cost us the game obviously","still had fun tho",
    "next match is ours","moral victory tbh","we scale"
};

static const char* tt_onPlayerJoinNamed[] = {
    "welcome %N","hey %N!","oh no %N is here","%N has arrived",
    "%N joined the party","everyone hide %N is here",
    "the lobby just got harder... jk welcome %N",
    "%N sup!","%N glad you could make it",
    "%N fresh meat... I mean welcome","%N oh this is gonna be fun",
    "%N your timing is perfect","%N entered the danger zone",
    "look who showed up! %N","%N ready to lose? jk jk",
    "%N welcome to the thunder dome","%N lets go!",
    "oh %N is here now its a party","%N just in time",
    "%N the legend arrives"
};

static const char* tt_randomBanter[] = {
    "this game is so addictive wtf","anyone else lagging or just me",
    "my grandma plays faster than you guys","server admin buff me pls",
    "i play better with my eyes closed","im not even trying rn",
    "imagine playing tron in 2026","this is my warm up round",
    "whos the best player here (its me)","gg ez (round didnt start yet)",
    "my rubber is bigger than yours","tactical dying btw",
    "can someone turn off the walls","nerf walls they too op",
    "plot twist: we are all bots","are we having fun yet",
    "this server runs on potato","where is the pause button",
    "how do I turn left again","instructions unclear got stuck in wall",
    "my gaming chair gives me +10 skill","who turned up the difficulty",
    "what if walls are just misunderstood",
    "the real treasure was the deaths along the way",
    "I should be sleeping rn","one more round I said 3 hours ago",
    "does anyone actually know the controls","my strategy is just vibes",
    "they should add battle royale to this","where is the gun shop",
    "can we get a pizza break","wifi held together by prayers",
    "my cycle needs an oil change","someone mod me I deserve it",
    "this is what peak performance looks like","call me the wall whisperer",
    "feel like a hamster in a maze","bold strategy lets see if it pays off",
    "just pretend I meant to do that","all chat no skill thats me",
    "winner gets bragging rights loser uninstalls","I play for the plot",
    "what time is it? tron time","do walls have feelings? asking for a friend",
    "I play this game competitively (im lying)","top 1% of wall avoiders",
    "I dont always die but when I do its spectacular",
    "can we get a timeout I need snacks","this is fine (its not fine)",
    "I came I saw I hit a wall","living my best tron life",
    "walls are just aggressive hugs","tron is basically chess but cooler",
    "someone should make a movie about my gameplay",
    "im in the zone... the death zone","anyone got spare rubber?",
    "that wall is looking at me funny","professional wall tester btw",
    "my mom thinks im good at this game","are we there yet",
    "plot twist: the walls were the friends we made along the way",
    "hold my rubber watch this","famous last words: I got this",
    "what could possibly go wrong","narrator: everything went wrong",
    "my cycle runs on pure chaos","I have a very particular set of skills",
    "im not lost im exploring","strategic positioning (im stuck)",
    "this is a certified hood classic","my plan is no plan",
    "trust the process","built different (dies immediately)",
    "I fear no wall... ok maybe that one","running on caffeine and hope",
    "my gameplay speaks for itself (it says help)",
    "im something of a scientist myself","just one more game (lie #47)",
    "the lag was emotional","I play for the character development",
    "every death is a learning opportunity (I learn nothing)",
    "im not camping im strategically waiting"
};

// Chat keyword/response pairs - massively expanded
static const char* tt_chatKeywords[][2] = {
    // Greetings
    {"hi", "oh hey there future victim"},
    {"hello", "hello is this the skill department"},
    {"hey", "hey hey hey"},
    {"sup", "the ceiling"},
    {"yo", "yooo"},
    {"hola", "hola amigo"},
    {"greetings", "greetings fellow wall dodger"},
    {"morning", "good morning to everyone except the walls"},
    {"evening", "good evening lets get this bread"},
    {"o/", "o/ hey there!"},
    {"\\o", "\\o right back at ya"},
    {"\\o/", "\\o/ party time!"},
    {"wave", "waves back enthusiastically"},
    {"howdy", "howdy partner ready to ride"},
    // Farewells
    {"bye", "dont leave the fun just started"},
    {"bb", "bb see ya next time!"},
    {"cya", "cya later alligator"},
    {"gn", "gn sleep well dream of walls"},
    {"gtg", "nooo dont go"},
    {"leaving", "one does not simply leave tron"},
    {"brb", "hurry back we need you (not really)"},
    {"afk", "even afk I play better than most"},
    {"bbl", "come back soon!"},
    // Common reactions
    {"lol", "glad I could entertain you"},
    {"lmao", "lmaooo we vibing"},
    {"lmfao", "ok that was genuinely funny"},
    {"rofl", "rolling on the floor dying (just like in game)"},
    {"haha", "hahaha yeah"},
    {"hehe", "hehe indeed"},
    {"xd", "XDDDD"},
    {"xdd", "XDDDDDDD"},
    {":)", ":)))"},
    {":(", "dont be sad be better"},
    {":D", ":DDDD"},
    {"<3", "<3 love you too"},
    {":3", ":3 meow"},
    {"uwu", "uwu notices your skill issue"},
    {"owo", "owo whats this? a wall?"},
    {"^^", "^^"},
    // Game reactions
    {"ez", "everything is ez when youre this good"},
    {"gg", "gg wp everyone"},
    {"ggwp", "gg wp indeed"},
    {"wp", "thanks you too"},
    {"gf", "good fight!"},
    {"ns", "ty ty"},
    {"nice", "ty ty I practice daily"},
    {"sick", "certified sick moment"},
    {"clean", "cleaner than a fresh install"},
    {"wow", "I know right? Im amazing"},
    {"omg", "I know I know Im amazing"},
    {"wtf", "just tron things"},
    {"bruh", "certified bruh moment indeed"},
    {"oof", "biggest oof of the century"},
    {"rip", "rest in pixels"},
    {"f", "f in the chat"},
    {"F", "F indeed"},
    {"damn", "ikr"},
    {"dang", "dang indeed"},
    {"wut", "you heard me"},
    {"wat", "exactly what you think"},
    {"huh", "confused? me too"},
    // Insults/Trash
    {"noob", "takes one to know one :)"},
    {"newb", "we all start somewhere... some of us just stay there"},
    {"nub", "nub? thats mr nub to you"},
    {"bad", "my mom thinks im cool tho"},
    {"trash", "recycling is important for the planet"},
    {"garbage", "one mans garbage is another mans treasure"},
    {"suck", "I suck at sucking does that count"},
    {"weak", "weak? I bench press walls"},
    {"pathetic", "pathetic is my middle name... wait"},
    {"terrible", "terribly good maybe"},
    {"awful", "awfully talented you mean"},
    {"worst", "worst? I prefer chaotically challenged"},
    {"useless", "useless? I provide entertainment value"},
    {"idiot", "idiot savant emphasis on savant"},
    {"stupid", "stupid is as stupid does and I do it well"},
    {"dumb", "dumb luck is still luck"},
    {"loser", "I dont lose I just havent won yet"},
    // Accusations
    {"hacker", "its called skill look it up"},
    {"hacks", "the only hack I use is my brain"},
    {"cheat", "nah just built different"},
    {"cheater", "I only cheat death (sometimes)"},
    {"aimbot", "I AM the aimbot"},
    {"wallhack", "wallhack? the walls hack ME"},
    {"lag", "excuses excuses"},
    {"lagging", "my lag makes me unpredictable actually"},
    {"laggy", "lag is just time travel"},
    {"ping", "my ping is a feature not a bug"},
    {"bot", "beep boop I am hooman"},
    {"ai", "I am 100% organic free range gamer"},
    {"macro", "my only macro is pure skill"},
    {"script", "my script is called talent.exe"},
    {"smurf", "im not a smurf im just naturally blue"},
    {"tryhard", "trying hard is literally the point"},
    {"sweaty", "sweaty palms sweaty wins"},
    // Compliments
    {"pro", "finally someone who recognizes talent"},
    {"good", "thanks I know"},
    {"great", "greatness recognizes greatness"},
    {"amazing", "I try my best (which is also the best)"},
    {"insane", "insanely good yes thank you"},
    {"beast", "rawr"},
    {"god", "im blushing"},
    {"legend", "legends never die (except when they do)"},
    {"king", "thanks for the crown"},
    {"queen", "yaaas queen"},
    {"goat", "greatest of all tron"},
    {"mvp", "most valuable player? if you insist"},
    {"carry", "my back hurts from carrying"},
    {"clutch", "clutch is my middle name"},
    {"cracked", "cracked at tron fr fr"},
    {"based", "extremely based thank you"},
    // Emotions
    {"mad", "stay mad stay bad"},
    {"angry", "anger leads to the dark side"},
    {"rage", "rage is just passion misspelled"},
    {"cry", "here let me give you something to cry about"},
    {"sad", "turn that frown upside down then crash into a wall"},
    {"happy", "happiness is a warm kill"},
    {"love", "I love you too <3"},
    {"hate", "haters are just confused fans"},
    {"salty", "pass the salt please"},
    {"toxic", "im not toxic im just brutally honest"},
    {"tilt", "tilted? try standing straight"},
    {"tilted", "untilt by touching grass"},
    // Questions
    {"how", "years of therapy... I mean training"},
    {"why", "because I can thats why"},
    {"what", "you heard me"},
    {"when", "right now"},
    {"where", "right behind you"},
    {"who", "me obviously"},
    {"really", "really really"},
    {"serious", "as serious as a wall to the face"},
    // Requests/Commands
    {"stop", "I literally cannot be stopped"},
    {"pls", "since you said pls... still no"},
    {"please", "manners wont save you here"},
    {"help", "no one can save you now"},
    {"run", "you cant outrun destiny"},
    {"wait", "walls dont wait and neither do I"},
    {"come", "come to papa"},
    {"fight", "you sure about that?"},
    {"1v1", "1v1 me bro I dare you"},
    {"rematch", "rematch? you want more pain?"},
    // Game terms
    {"rubber", "rubber is for amateurs I use pure skill"},
    {"wall", "walls are just aggressive decorations"},
    {"walls", "walls are my friends (sometimes)"},
    {"speed", "my cycle goes brrrrr"},
    {"brake", "brakes are for quitters"},
    {"turn", "I turn heads and corners"},
    {"zone", "the zone fears me"},
    {"fortress", "I AM the fortress"},
    {"sumo", "more like su-NO for you"},
    {"ctf", "capture the flag? I capture everything"},
    {"score", "scoreboard speaks for itself"},
    {"round", "every round is my round"},
    {"match", "match point? more like match ME"},
    // Memes/Internet
    {"cope", "cope seethe mald repeat"},
    {"seethe", "seething? try breathing"},
    {"mald", "balding from malding"},
    {"ratio", "ratio + L + skill issue"},
    {"cap", "no cap fr fr"},
    {"nocap", "on god no cap"},
    {"sus", "kinda sus ngl"},
    {"cringe", "ur face is cringe"},
    {"mid", "mid? Im at least high tier"},
    {"bussin", "bussin fr fr no cap"},
    {"fire", "fire like my gameplay"},
    {"lit", "lit af"},
    {"vibe", "just vibing and thriving"},
    {"flex", "flexing is my cardio"},
    {"yeet", "yeeted into the wall"},
    {"pog", "poggers moment"},
    {"poggers", "mega poggers"},
    {"kek", "kekw"},
    {"pepega", "pepega but in a good way"},
    {"monka", "monkaS"},
    {"sadge", "sadge indeed"},
    {"copium", "inhaling copium rn"},
    {"hopium", "overdosing on hopium"},
    {"sheesh", "sheeeeeesh"},
    {"bussin", "bussin respectfully"},
    {"no cap", "on god"},
    {"fr", "fr fr on jah"},
    {"frfr", "frfr no cap on god"},
    {"ngl", "ngl youre right"},
    {"tbh", "tbh yeah"},
    {"btw", "btw im better than all of you"},
    {"imo", "imo walls should be illegal"},
    {"idk", "idk either but here we are"},
    {"idc", "idc I just play for fun"},
    {"smh", "smh my head"},
    {"ffs", "for real tho"},
    {"brb", "brb getting better at tron"},
    {"nvm", "nvm I already forgot"},
    // Misc
    {"spam", "spamming is an art form"},
    {"win", "winning is my default setting"},
    {"lose", "I dont lose I just learn aggressively"},
    {"die", "death is just a respawn timer"},
    {"kill", "violence is never the answer... except here"},
    {"fast", "I was born fast"},
    {"slow", "slow and steady gets wrecked"},
    {"fair", "everything is fair in love and tron"},
    {"op", "thats what they call me"},
    {"buff", "I AM the buff"},
    {"nerf", "you cant nerf pure talent"},
    {"dodge", "if you can dodge a wall you can dodge a ball"},
    {"timing", "my timing is impeccable"},
    {"strat", "my strategy is to be better than everyone"},
    {"sorry", "apology not accepted >:)"},
    {"no", "yes"},
    {"yes", "no... wait"},
    {"ok", "k"},
    {"k", "potassium"},
    {"lul", "lulw"},
    {"any", "any truers?"},
    {"true", "truuuue"},
    {"same", "same tbh"},
    {"mood", "biggest mood"},
    {"facts", "nothing but facts"},
    {"real", "keeping it real"},
    {"respect", "respect earned"},
    {"ty", "yw :)"},
    {"thx", "np!"},
    {"thanks", "youre welcome citizen"},
    {"np", "np anytime"},
    {"gl", "gl to everyone except my enemies"},
    {"hf", "always having fun"},
    {"glhf", "gl hf dont die (you will)"},
    {"nt", "nt almost had it"},
    {"close", "closer than you think"},
    {"lucky", "100% skill 0% luck"},
    {"unfair", "life isnt fair deal with it"},
    {"boring", "boring? have you tried being better"},
    {"fun", "this IS fun right? RIGHT?"},
    {"nice shot", "ty I trained for this moment"},
    {"teach", "my rates are expensive"},
    {"mentor", "I charge by the death"},
    {"tip", "tip: dont die"},
    {"advice", "my advice: git gud"},
    {"lmk", "will do chief"},
};

// ============ FRIENDLY MODE (polite, competitive-safe) ============
static const char* tt_friendlyKeywords[][2] = {
    {"gg", "gg wp!"},
    {"ggwp", "gg wp! good game"},
    {"gf", "good fight!"},
    {"gj", "thanks! :)"},
    {"wp", "thanks, you too!"},
    {"wd", "ty! :)"},
    {"ns", "thanks!"},
    {"nice", "ty!"},
    {"bb", "bb! cya next time"},
    {"bye", "bye! was fun"},
    {"cya", "cya! take care"},
    {"gn", "gn! sleep well"},
    {"hi", "hey! :)"},
    {"hello", "hello! :)"},
    {"hey", "hey!"},
    {"o/", "o/ :)"},
    {"\\o", "\\o"},
    {"\\o/", "\\o/"},
    {"yo", "yo! :)"},
    {"sup", "hey! whats up"},
    {"howdy", "howdy!"},
    {"hola", "hola! :)"},
    {"lol", "haha :D"},
    {"lmao", "lmao XD"},
    {"haha", "haha :)"},
    {"xd", "XD"},
    {":)", ":)"},
    {":D", ":D"},
    {"<3", "<3"},
    {":3", ":3"},
    {"^^", "^^"},
    {"gl", "gl hf!"},
    {"glhf", "gl hf! :)"},
    {"hf", "hf!"},
    {"ty", "yw! :)"},
    {"thx", "np!"},
    {"thanks", "np :)"},
    {"sorry", "all good!"},
    {"mb", "no worries!"},
    {"np", "np :)"},
    {"nt", "nt! almost had it"},
    {"close", "yeah that was close!"},
    {"fun", "having a blast!"},
    {"good game", "gg! was fun :)"},
    {"respect", "respect! :)"},
    {"pro", "thanks! you too"},
    {"clutch", "ty! that was intense"},
    {"beast", "haha thanks"},
    {"legend", "no u :)"},
    {"king", "no u the king :)"},
    {"goat", "haha ty!"},
    {"amazing", "thanks! :D"},
    {"sick", "ty!"},
    {"clean", "thanks! :)"},
    {"good", "ty! you too"},
    {"great", "thanks! great game"},
};

static const char* tt_friendlyMatchWin[] = {
    "gg wp everyone!", "good game! that was fun", "gg! well played all",
    "great match! gg", "gg! close one", "wp everyone! :)"
};

static const char* tt_friendlyMatchLose[] = {
    "gg wp!", "good game!", "well played!", "gg! close one",
    "wp! that was fun", "gg :)"
};

static const char* tt_friendlyGreetings[] = {
    "hey everyone! :)", "hi! gl hf", "hello! :)", "hey! gg gl",
    "hi all! :)", "yo! gl hf everyone"
};

#endif // E_TRASH_TALK_DATA_H
